version: "3.8"
services:

  mongo:
    container_name: clump-db
    image: mongo:latest
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
    - "27018:27017"
    volumes:
      - ./data:/data/db
    networks:
      - clump-network

  api:
    container_name: clump-server-api
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/user/src/app
    networks:
      - clump-network
    depends_on:
      - mongo

networks:
  clump-network:
    driver: bridge